### PR TITLE
add a missing   Wizard.CloseDialog (bsc#1194279)

### PR DESCRIPTION
**Pull request by msmeissn**
## Problem

Wizard layout problem when going back ... as the wizard is not closed.

- https://bugzilla.suse.com/show_bug.cgi?id=1194279
- *openQA link*

## Solution

Added missing Wizard.CloseDialog as suggested.

## Testing

- untested

## Screenshots

*If the fix affects the UI attach some screenshots here.*

### CODE REVIEW

**Comment by msmeissn** [comment]
@lnussel also for you, as you wrote the code originally

**Comment by lnussel** [comment]
lgtm

**Comment by dgdavid** [comment]
Hi, thanks a lot for the fix.

I only miss the version bump and changelog. See the 4th step at https://yastgithubio.readthedocs.io/en/latest/contributing/#code-changes I can take care if you are in a hurry.

Also, I think you want to send that change to SP4, right? If so, we should start making the PR against the SLE-15-SP4 branch instead of master.

**Comment by mvidner** [comment]
Thanks all, #9 supersedes this.

**Pull request closed without merging**
